R&DChartSite/Controllers/InSiteController.cs
using R_DChartSite.BussinessLayer;
using R_DChartSite.Entities;
using R_DChartSite.Entities.ValueObjects;
using R_DChartSite.Filters;
using RDChartSite.BussinessLayer;
using RDChartSite.BussinessLayer.Results;
using RDChartSite.Entities;
using RDChartSite.Entities.ValueObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RDChartSite.Controllers
{
    //[Auth]
    public class InSiteController : Controller
    {
        private ProjectsManager projectsManager = new ProjectsManager();
        private ActivitiesManager activitiesManager = new ActivitiesManager();
        private UserManager userManager = new UserManager();
        private FormsManager formManager = new FormsManager();

        // GET: InSite
        public ActionResult DailySchedule()
        {
            var viewModel = new DailyScheduleViewModel
            {
                Projects = projectsManager.List(),
                DailyActivity = new DailyActivity(),
                HourlyActivity = new HourlyActivity()
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DailySchedule(DailyScheduleViewModel viewModel)
        {
            if (Session["Login"] != null)
            {
                var user = Session["Login"] as Users;
                var userId = user.Id;
                var userToUpdate = userManager.Find(x => x.Id == userId);
                string dateString = Request.Form["DailyActivities.Date"];
                DateTime date;
                if (DateTime.TryParse(dateString, out date))
                {
                    //günlük kayıt var mı kontrolü
                    if (activitiesManager.DailyExistControl(date))
                    {
                        List<HourlyActivity> hourlyActivities = new List<HourlyActivity>();
                        var existingdaily = activitiesManager.Find(x => x.Date == date);
                        existingdaily.HourlyActivities = new List<HourlyActivity>();
                        for (int i = 8; i < 24; i++)
                        {
                            TimeSpan time = TimeSpan.FromHours(i);
                            bool existingrecord = activitiesManager.HourlyControl(userId, date, time);
                            var hourlyDescription = Request.Form[$"HourlyActivities[{i - 8}].Description"];
                            if (!existingrecord)
                            {
                                if (!string.IsNullOrEmpty(hourlyDescription))
                                {
                                    var hourlyActivity = new HourlyActivity
                                    {
                                        DailyActivityId = existingdaily.Id,
                                        Time = time,
                                        Description = hourlyDescription,
                                        ProjectCode = Request.Form[$"HourlyActivities[{i - 8}].ProjectCode"]
                                    };

                                    if (hourlyActivity.ProjectCode != "Proje Kodu Seçiniz")
                                    {
                                        existingdaily.HourlyActivities.Add(hourlyActivity);
                                    }
                                    else
                                    {
                                        ModelState.AddModelError($"HourlyActivities[{i + 16}].ProjectCode", $"{i}:00 saatindeki girdinize ait proje kodunu girmediniz.");

                                    }
                                }
                            }
                            else
                            {
                                ModelState.AddModelError($"HourlyActivities[{i + 16}].Description", $"{i}:00 saatindeki girdinize ait kaydınız zaten mevcuttur.");

                            }
                        }
                        for (int i = 0; i < 8; i++)
                        {
                            TimeSpan time = TimeSpan.FromHours(i);
                            bool existingrecord = activitiesManager.HourlyControl(userId, date, time);
                            var hourlyDescription = Request.Form[$"HourlyActivities[{i + 16}].Description"];
                            if (!existingrecord)
                            {
                                if (!string.IsNullOrEmpty(hourlyDescription))
                                {
                                    var hourlyActivity = new HourlyActivity
                                    {
                                        DailyActivityId = existingdaily.Id,
                                        Time = TimeSpan.FromHours(i),
                                        Description = hourlyDescription,
                                        ProjectCode = Request.Form[$"HourlyActivities[{i + 16}].ProjectCode"]
                                    };
                                    if (hourlyActivity.ProjectCode != "Proje Kodu Seçiniz")
                                    {
                                        existingdaily.HourlyActivities.Add(hourlyActivity);
                                    }
                                    else
                                    {
                                        ModelState.AddModelError($"HourlyActivities[{i + 16}].ProjectCode", $"{i}:00 saatindeki girdinize ait proje kodunu girmediniz.");

                                    }
                                }
                            }
                            else
                            {
                                ModelState.AddModelError($"HourlyActivities[{i + 16}].Description", $"{i}:00 saatindeki girdinize ait kaydınız zaten mevcuttur.");

                            }
                        }

                        activitiesManager.Update(existingdaily);
                        return View(viewModel);
                    }
                    else//günlük kayıt yoksa yenisini oluşturur
                    {
                        var dailyActivity = new DailyActivity
                        {
                            UserId = userToUpdate.Id,
                            Date = date,
                            HourlyActivities = new List<HourlyActivity>()
                        };
                        for (int i = 8; i < 24; i++)
                        {
                            TimeSpan time = TimeSpan.FromHours(i);
                            bool existingrecord = activitiesManager.HourlyControl(userId, date, time);
                            var dailyexits = activitiesManager.Find(x => x.Id == dailyActivity.Id);
                            var hourlyDescription = Request.Form[$"HourlyActivities[{i - 8}].Description"];
                            if (!existingrecord)
                            {
                                if (!string.IsNullOrEmpty(hourlyDescription))
                                {
                                    var hourlyActivity = new HourlyActivity
                                    {
                                        DailyActivityId = dailyActivity.Id,
                                        Time = time,
                                        Description = hourlyDescription,
                                        ProjectCode = Request.Form[$"HourlyActivities[{i - 8}].ProjectCode"]
                                    };

                                    if (hourlyActivity.ProjectCode != "Proje Kodu Seçiniz")
                                    {
                                        dailyActivity.HourlyActivities.Add(hourlyActivity);
                                    }
                                    else
                                    {
                                        ModelState.AddModelError($"HourlyActivities[{i + 16}].ProjectCode", $"{i}:00 saatindeki girdinize ait proje kodunu girmediniz.");

                                    }
                                }
                            }
                            else
                            {
                                ModelState.AddModelError($"HourlyActivities[{i + 16}].Description", $"{i}:00 saatindeki girdinize ait kaydınız zaten mevcuttur.");

                            }
                        }
                        for (int i = 0; i < 8; i++)
                        {
                            TimeSpan time = TimeSpan.FromHours(i);
                            bool existingrecord = activitiesManager.HourlyControl(userId, date, time);
                            var hourlyDescription = Request.Form[$"HourlyActivities[{i + 16}].Description"];
                            if (!existingrecord)
                            {
                                if (!string.IsNullOrEmpty(hourlyDescription))
                                {
                                    var hourlyActivity = new HourlyActivity
                                    {
                                        DailyActivityId = dailyActivity.Id,
                                        Time = TimeSpan.FromHours(i),
                                        Description = hourlyDescription,
                                        ProjectCode = Request.Form[$"HourlyActivities[{i + 16}].ProjectCode"]
                                    };
                                    if (hourlyActivity.ProjectCode != "Proje Kodu Seçiniz")
                                    {
                                        dailyActivity.HourlyActivities.Add(hourlyActivity);
                                    }
                                    else
                                    {
                                        ModelState.AddModelError($"HourlyActivities[{i + 16}].ProjectCode", $"{i}:00 saatindeki girdinize ait proje kodunu girmediniz.");

R&DChartSite/Views/InSite/DailySchedule.cshtml
@model R_DChartSite.Entities.ValueObjects.DailyScheduleViewModel
@{
    
    ViewBag.Title = "Günlük Aktivite Formu";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<div class="container"style="width:100%;height:100%;" id="tables">

    @using (Html.BeginForm("DailySchedule", "InSite", FormMethod.Post, new { onsubmit = "return validateForm()" }))
    {
        @Html.AntiForgeryToken()
        @Html.Partial("_DailyTable")

        <div class="container m-lg-auto">
            <div class="text-end">
                <button class="btn btn-success " style="width:80px">Ekle</button>
                <input type="reset" class="btn btn-danger"/>
            </div>
        </div>
    }
</div>

R&DChartSite/Views/InSite/Dashboard.cshtml
@using R_DChartSite.Entities
@using RDChartSite.Entities
@using RDChartSite.BussinessLayer
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
@{
    Users user = new Users();
    UserManager userManager = new UserManager();
    ProjectsManager projectsManager = new ProjectsManager();
    ActivitiesManager activitiesManager = new ActivitiesManager();
    List<Projects> currentusersprojects = new List<Projects>();
    Users currentUser = new Users();

    if (Session["Login"] != null)
    {
        user = Session["Login"] as Users;
        currentUser = userManager.Find(x => x.Id == user.Id);
    }
    DailyActivity usersactivities = activitiesManager.Find(x => x.UserId == currentUser.Id);
    List<Users> users = userManager.GetAllUsersIncludingProjects();
}
<style>
    .dropup button {
        color: black;
        padding-bottom: 5px;
    }
    .table tbody tr:last-child {
        border-bottom-color:transparent;
    }
    .dropdown-menu-up {
        top: auto;
        bottom: 100%;
        transform: translateY(-5px);
    }

    .card {
        box-shadow: -4px 6px 8px -1px rgba(122,122,122,0.67);
        border-radius: 10px;
    }
    .card-header {
        background-color: #151515;
    }

    .numbercards {
        border-left: 5px solid black;
    }

        .numbercards:hover {
            color: white;
            background-color: black;
            transform: scale(1.05);
            transition: transform 0.3s ease-in-out;
        }

            .numbercards:hover .bi::after {
                color: white;
            }

    .card-body {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 15px;
    }
</style>
<div class="container">
    <div class="row justify-content-between">
        <div class="col-sm-3 mb-4">
            <div class="card numbercards users">
                <div class="card-body d-flex align-items-center justify-content-center">
                    <i class="bi bi-people-fill" style="font-size: 80px; color: #992d2d;"></i>
                    <div class="ms-3">
                        <h1 class="mb-0">@userManager.TotalUserCount()</h1>
                        <p class="mb-0" style="font-size: 20px;">Kullanıcı</p>
                    </div>
                </div>
            </div>
            <div class="card numbercards projects mt-4">
                <div class="card-body d-flex align-items-center justify-content-center">
                    <i class="bi bi-list-task" style="font-size: 80px; color: #992d2d;"></i>
                    <div class="ms-3">
                        <h1 class="mb-0">@projectsManager.TotalProjectsCount()</h1>
                        <p class="mb-0" style="font-size: 20px;">Proje</p>
                    </div>
                </div>
            </div>
            <div class="card numbercards activities mt-4">
                <div class="card-body d-flex align-items-center justify-content-center">
                    <i class="bi bi-calendar4-week" style="font-size: 80px; color: #992d2d;"></i>
                    <div class="ms-3">
                        <h1 class="mb-0">@activitiesManager.GetHourlyActivityCountInWeek()</h1>
                        <p class="mb-0" style="font-size: 20px;">Haftalık </p>
                        <p class="mb-0" style="font-size: 20px;">Aktivite</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-9 mb-4">
            <div class="col-lg-12">
                <div class="card" style="height: 510px;">
                    <div class="card-header text-center text-light ">
                        <h6 class="card-text ">PROJE/ÇALIŞAN DAĞILIMI</h6>
                    </div>
                    <div class="card-body ">
                        <canvas id="doughnutchart" style="max-height: 100%;"></canvas>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-sm-12 mb-4">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header text-center text-light">
                        <h6 class="card-text ">PROJELERİN SAATLİK DAĞILIMI</h6>
                    </div>
                    <div class="card-body">
                        <canvas id="linechart"></canvas>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="row ">
        <div class="col">
            <div class="card">
                <div class="card-header text-center text-light">
                    <h6 class="card-text ">ÇALIŞAN LİSTESİ</h6>
                </div>
                <div class="card-body">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">İsim</th>
                                <th scope="col">Soyisim</th>
                                <th scope="col">Proje Sayısı</th>
                                <th scope="col">Toplam Saat</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var data in users)
                                {
                                    <tr>
                                        <th scope="row">@data.Id</th>
                                        <td>@data.Name</td>
                                        <td>@data.Surname</td>
                                        <td>
                                            <div class="dropup">
                                                <button class="btn btn-link dropdown-toggle project-count" type="button" id="projectDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    @data.Projects.Count()
                                                </button>
                                                <div class="dropdown-menu dropdown-menu-up" aria-labelledby="projectDropdown">
                                                    @foreach (var project in data.Projects)
                                                    {
                                                        <a class="dropdown-item" href="#">@project.ProjectName</a>
                                                    }
                                                </div>
                                            </div>
                                        </td>
                                        <td>@activitiesManager.GetHourlyActivityCount(data.Id)</td>
                                    </tr>
                                }
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

<div style="display:none">
    <table class="table table-sm" id="users">
        <tbody>
            @{
                Dictionary<string, int> UserCountForProject = projectsManager.UsersForProjectsCount();
                foreach (var item in UserCountForProject)
                {
                    string projectName = projectsManager.FindProjectNameByCode(item.Key);
                    if (item.Value > 0)
                    {
                        <tr>
                            <td>@projectName</td>
                            <td>@item.Value</td>
                        </tr>
                    }
                }
            }
        </tbody>
    </table>
</div>
<div style="display:none">
    <table class="table table-sm" id="hours">
        <tbody>
            @{
                Dictionary<string, int> timeCountByProjectCode = activitiesManager.GetTimeCountByProjectCode();
                foreach (var item in timeCountByProjectCode)
                {
                    string projectName = projectsManager.FindProjectNameByCode(item.Key);
                    <tr>
                        <td>@projectName</td>
                        <td>@item.Value</td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('.projects').click(function () {
            window.location.href = '/InSite/ProjectsDashboardList';
        });
    });

    $(document).ready(function () {
        $('.activities').click(function () {
            window.location.href = '/Insite/WeeklyActivities';
        });
    });

    $(document).ready(function () {
        $('.users').click(function () {
            window.location.href = '/Users/Index';
        });
    });
    $(document).ready(function () {
        $('.project-count').on('click', function () {
            $(this).siblings('.dropdown-menu').toggleClass('show');
        });
    });
</script>
<script src="~/Scripts/DoughnutChart.js"></script>
<script src="~/Scripts/LineChart.js"></script>

R&DChartSite/Views/InSite/FormApprovalPage.cshtml
@using R_DChartSite.Entities
@model OffDayForms
@{
    ViewBag.Title = "FormApprovalPage";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
<style>
    .card {
        border: 1px solid #e0e0e0;
        border-radius: 5px;
        padding: 10px;
        background-color: #f9f9f9;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        max-width: 400px;
        margin: 0 auto;
    }
</style>
<div class="card">
    <h2>İzin Talep Formu</h2>
    <p>Aşağıda belirtilen izin formunun bilgilerini içeren bir talep alındı:</p>
    <p>
        Ad Soyad: @Model.User.Name @Model.User.Surname<br>
        Başlangıç Tarihi: @Model.StartDate<br>
        Dönüş Tarihi: @Model.ReturnDate<br>
        İzin Türü: @Model.PType<br>
        Başlangıç Saati: @Model.StartTime<br>
        Dönüş Saati: @Model.ReturnTime<br>
        Proje Kodu: @Model.ProjectCode<br>
        Açıklama: @Model.Description<br>
        İzin Nedeni: @Model.Reason
    </p>
    <form method="post">
        <input type="hidden" name="FormGuid" value="@Model.FormGuid" />
        <button type="submit" name="approval" value="true" class="btn btn-outline-success">Onayla</button>
        <button type="submit" name="approval" value="false" class="btn btn-outline-danger">Reddet</button>
    </form>
</div>

R&DChartSite/Views/InSite/MonthlySchedule.cshtml
@model RDChartSite.Entities.ValueObjects.MonthlyDataModel
@using RDChartSite.BussinessLayer
@using R_DChartSite.Entities
@using RDChartSite.Entities

@{
    ViewBag.Title = "Aylık Aktivite Takibi";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

@{
    UserManager userManager = new UserManager();
    Users user = new Users();
    if (Session["Login"] != null)
    {
        user = Session["Login"] as Users;

    }
}

<br />
<div id="partialcontainer">
    @Html.Partial("_PartialMonthly")
</div>

R&DChartSite/Views/InSite/OffDayForm.cshtml
@model R_DChartSite.Entities.ValueObjects.OffDayFormsViewModel
@using RDChartSite.BussinessLayer
@using R_DChartSite.Entities
@using RDChartSite.Entities
@{
    ViewBag.Title = "İzin Formu";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    Users user = new Users();
    Users currentUser = new Users();
    UserManager userManager = new UserManager();
    TeamsManager teamsManager = new TeamsManager();
    if (Session["Login"] != null)
    {
        user = Session["Login"] as Users;
        currentUser = userManager.Find(x => x.Id == user.Id);
    }
    List<int> LeaderIds = teamsManager.GetLeadersList();
}
<style>
    .modal-dialog {
        display: flex;
        align-items: center;
    }
</style>

<link href="~/css/style.css" rel="stylesheet" />
<!-- CARD CONTENT -->
@using (Html.BeginForm())
{
    @Html.ValidationSummary(false)
    <div class="container mb-5">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-8">
                <div class="card">
                    <!-- CARD HEADER -->
                    <div class="card-header mx-auto p-2">
                        <div class="container-fluid mx-auto p-2">
                            <label class="navbar-brand " href="/Home/Login" style="font-size: large;">
                                <img src="../img/2saydam.png" alt="Logo" width="40" height="40"
                                     class="d-inline-block align-text-center">
                                <b>ORTEM ELEKTRONİK</b>
                            </label>
                        </div>
                    </div>
                    <hr>
                    <!-- CARD BODY -->
                    <div class="card-body">
                        <div class="form-group d-flex">
                            <div class="mr-3">
                                <label for="Name">Ad:</label>
                                <input type="text" name="Name" value="@currentUser.Name" placeholder="@currentUser.Name" disabled class="border-0" />
                            </div>
                            <div class="mr-3">
                                <label for="Name">Soyad:</label>
                                <input type="text" name="Surname" value="@currentUser.Surname" placeholder="@currentUser.Surname" disabled class="border-0" />
                            </div>
                            <div>
                                <label for="Name">Görevi:</label>
                                <input type="text" name="UserTeam" value="@teamsManager.IdtoName(currentUser.TeamId)" placeholder="@teamsManager.IdtoName(currentUser.TeamId)" disabled class="border-0" />
                            </div>
                        </div>
                        <div class="d-flex">
                            <div class="m-2">
                                <div class="form-group">
                                    <label for="Name">Gidiş Tarih:</label>
                                    <input type="date" name="StartDate" value="" />
                                </div>
                                <div class="form-group">
                                    <label for="Name">Geliş Tarih:</label>
                                    <input type="date" name="ReturnDate" value="" />
                                </div>
                            </div>
                            <div class="form-check">
                                <div class="d-flex">
                                    <div class="m-2">
                                        <input type="radio" id="priced" name="PType" value="Ücretli">
                                        <label for="priced">Ücretli İzin</label><br>
                                    </div>
                                    <div class="m-2">
                                        <input type="radio" id="unpriced" name="PType" value="Ücretsiz">
                                        <label for="unpriced">Ücretsiz İzin</label><br>
                                    </div>
                                    <div class="m-2">
                                        <input type="radio" id="vizite" name="PType" value="Vizite">
                                        <label for="vizite">Vizite</label>
                                    </div>
                                </div>
                                <div class="m-2">
                                    <div class="form-group">
                                        <label for="Name">Geliş Saat:</label>
                                        <input class="" type="time" name="StartTime" value="" />
                                    </div>
                                    <div class="form-group">
                                        <label for="Name">Gidiş Saat:</label>
                                        <input class="" type="time" name="ReturnTime" value="" />
                                    </div>
                                    <div class="form-group">
                                        <label for="ProjectCode">Proje Kodu:</label>
                                        <input type="text" name="ProjectCode" value="" />
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="form-group">
                            <label for="Description">İzin Açıklaması:</label>
                            <input type="text" name="Description" class="w-100" />
                        </div>
                        <div class="form-group d-flex justify-content-around">
                            <div class="m-2">
                                <input type="radio" id="Hastalık" name="Reason" value="Hastalık">
                                <label for="Hastalık">Hastalık</label><br>
                                <input type="radio" id="YıllıkIzın" name="Reason" value="Yıllık İzin">
                                <label for="YıllıkIzın"> Yıllık İzin</label><br>
                            </div>
                            <div class="m-2">
                                <input type="radio" id="Mazeret" name="Reason" value="Mazeret">
                                <label for="Mazeret">Mazeret</label><br>
                                <input type="radio" id="Dogum" name="Reason" value="Doğum">
                                <label for="Dogum">Doğum</label><br>
                            </div>
                            <div class="m-2">
                                <input type="radio" id="Olum" name="Reason" value="Ölüm">
                                <label for="Olum">Ölüm</label><br>
                                <input type="radio" id="Evlilik" name="Reason" value="Evlilik">
                                <label for="Evlilik">Evlilik</label><br>
                            </div>
                        </div>
                        <div class="form-group d-flex">
                            <div class="m-2">
                                <small for="TotalPermission">Toplam hakedilen izin(Gün/Saat):</small>
                                <input type="number" name="TotalPermission" value="" />
                            </div>
                            <div class="m-2">
                                <small for="UsingPermission">Kullanılacak izin(Gün/Saat):</small>
                                <input type="number" name="UsingPermission" value="" />
                            </div>
                        </div>

                        <div class="form-group d-flex">
                            <select name="MailTo">
                                @foreach (var item in LeaderIds)
                                {
                                    <option value="@item">@userManager.GetUserNameById(item) </option>
                                }
                            </select>
                        </div>

                        <div class="visually-hidden">
                            <input type="text" name="UserId" value="@currentUser.Id" />
                        </div>
                        <label><b>@currentUser.TotalPermission / @currentUser.RemainingPermission yıllık izin gününüz kalmıştır.</b>  </label>
                    </div>
                    <div class="card-footer">
                        <div class="m-2">
                            <input type="checkbox" id="userapproval" name="name" value="aprrovedbyuser" />
                            <label for="userapproval">Bu talep formu ile @DateTime.Now.Year yılına ait yıllık iznimden X gün kullanmayı talep ediyorum.</label>
                        </div>
                        <div class="d-flex justify-content-center">

                            <button class="btn btn-success d-flex " type="submit">Gönder</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="notificationModal" tabindex="-1" aria-labelledby="notificationModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="notificationModalLabel">Bildirim</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-center">
                    <i class="bi bi-check-circle display-1 text-success"></i>
                    <p class="mt-3">@TempData["Notification"]</p>
                </div>
            </div>
        </div>
    </div>
}
<script>
        $(document).ready(function () {
            var notification = '@TempData["Notification"]';
            if (notification.trim() !== '') {
                $('#notificationModal').modal('show');
            }
        });
</script>